### PR TITLE
Add term hierarchy as replacement variable.

### PR DESCRIPTION
**Pull request by afercia**
## Context

* Please see https://github.com/Yoast/featurerequests/issues/426 and the test instructions on [the related PR](https://github.com/Yoast/wordpress-seo/pull/14497).

## Summary

This PR can be summarized in the following changelog entry:

* Adds the term ancestors hierarchy as a taxonomy replacement variable.

Fixes https://github.com/Yoast/featurerequests/issues/426

### CODE REVIEW

**Comment by afercia** [comment]
The build fails for unrelated reasons. Tests fail also on trunk, seems related to `valueAddedTaxIncluded`.

**Comment by afercia** [comment]
Looks like something went wrong between the [hotfix/12.6.1 merge](https://github.com/Yoast/wpseo-woocommerce/commit/3314188f990918196718b31b901f1b27b7b54337) and [the pull request for the schema color property](https://github.com/Yoast/wpseo-woocommerce/pull/532). On trunk there's still a `valueAddedTaxIncluded` in a test. Removed in the last commit. @hansjovis when you have a chance, please let me know if that's OK 🙂

**Comment by hansjovis** [comment]
@afercia : I checked the code, and removing it is OK 🙂.

In the hotfix, we decided to remove the property that says if taxes are included when tax calculations are disabled in WooCommerce. Since we cannot tell anymore if the user enters prices with or without tax.

**Comment by afercia** [comment]
Thanks for double checking!

**Comment by karlijnbok** [comment]
CR & Acceptance: 👍(See https://github.com/Yoast/wordpress-seo/pull/14497)

**Pull request merged**
