### PR TITLE
Add option to display the price in Schema and OpenGraph with tax included

### PR DESCRIPTION
**Pull request by jdevalk**
## Summary

This PR can be summarized in the following changelog entry:

* Adds an option to display the price in Schema and OpenGraph _with_ tax included.

## Relevant technical choices:

* Moved OpenGraph functionality to its own class and gave it a hook that all the specific fields hook on to, so people can unhook specific fields.
* Increased test coverage to 100% for the new `woocommerce-opengraph.php` class.
* Increased test coverage to 100% for the new `woocommerce-utils.php` class.
* Increased test coverage to 100% for the `woocommerce-schema.php` class.

## Test instructions

This PR can be tested by following these steps:

* Enable tax in your WooCommerce install (on the General tab of WooCommerce settings).
* Set the new setting in the admin to true:

Screen Shot 2020-01-22 at 11 32 10

* Add a tax rate and play with the settings on the Tax tab, the outcomes should be the same on the frontend as they are in the schema.

Fixes https://github.com/Yoast/featurerequests/issues/422

### CODE REVIEW

**Comment by jcomack** [comment]
Acceptance done 👍

**Comment by jdevalk** [comment]
## Updated instructions

* Go to WooCommerce -> Settings -> General
* Check "Enable taxes", click Save
* Go to the new "Tax" tab, WooCommerce -> Settings -> Tax
* Go to "Standard rates" -> add a tax rate, applicable to everyone, like so:

Screenshot 2020-02-06 at 15 31 20

* Go to WooCommerce -> Settings -> Tax -> Tax options
* Set "Display prices in the shop" to "Including tax"
* Go to SEO -> WooCommerce SEO, the new option should show up

With the option _enabled_, the price in the OpenGraph and Schema output should mimic the price shown on the page itself. With the option _disabled_, the price in Schema and OpenGraph should exclude tax.

**Comment by dariaknl** [comment]
Acceptance testing:

**Case 1**
1. `Enable taxes` in Woocommerce is set.
2. `Standard rates` is set to applicable to everyone and Rate 80%.
3. `Prices entered with tax` is set to `No, I will enter prices exclusive of tax`.
4. `Prices in OpenGraph and Schema include tax` is enabled in SEO Woocommerce.
5. Product is created, price is set to 6 EUR.

Result:
* frontend - €10.80
* `<meta property="product:price:amount" content="10.80" />`
Screenshot 2020-02-07 at 13 24 16


**Case 2**
1. `Enable taxes` in Woocommerce is set.
2. `Standard rates` is set to applicable to everyone and Rate 80%.
3. `Prices entered with tax` is set to `No, I will enter prices exclusive of tax`.
4. `Prices in OpenGraph and Schema include tax` is DISABLED in SEO Woocommerce.
5. Product is created, price is set to 6 EUR.

Result:
* frontend - €10.80
* `<meta property="product:price:amount" content="6.00" />`
Screenshot 2020-02-07 at 13 26 19


**Case 3**
1. `Enable taxes` in Woocommerce is set.
2. `Standard rates` is set to applicable to everyone and Rate 80%.
3. `Prices entered with tax` is set to `Yes, I will enter prices inclusive of tax`.
4. `Prices in OpenGraph and Schema include tax` is enabled in SEO Woocommerce.
5. Product is created, price is set to 6 EUR.

Result:
* frontend - 6 EUR
* `<meta property="product:price:amount" content="6.00" />`
Screenshot 2020-02-07 at 13 29 13

**Comment by dariaknl** [comment]
**Additional cases**
Tested with different settings from Woocommerce `Tax options` and `General` price data within product - whenever the price is being changed with taxez on frontend, we output it accordingly in a `"product:price:amount"` and schema.

**Comment by jdevalk** [comment]
Nice!

**Pull request merged**
