### PR TITLE
Stop enqueueing a non existing file.

### LINKED ISSUE #176: Console error when clicking WooCommerce in the Yoast SEO plugin menu.
RC5.8

When clicking the WooCommerce tab in the Yoast SEO plugin, there is a console error.

woocommerce_seo_-_yoast_seo_ _bob_loblaw_s_law_blog_ _wordpress

woocommerce_seo_-_yoast_seo_ _bob_loblaw_s_law_blog_ _wordpress

### PR DESCRIPTION
**Pull request by andizer**
## Summary

This PR can be summarized in the following changelog entry:
* Fixes a bug where a non-existing file has been enqueued.

## Test instructions

This PR can be tested by following these steps:

* Checkout `trunk` and go to the WooCommerce SEO page in the admin menu.
* A console error should be visible.
* Checkout this branch and see the error being solved.

Fixes #176

### CODE REVIEW

**Comment by moorscode** [comment]
Did you check if this file does not exist entirely anymore or has just been moved in Yoast SEO (to a dist folder perhaps)?

**Comment by moorscode** [comment]
See related issue: https://github.com/Yoast/wpseo-news/issues/323

**Comment by andizer** [comment]
Good catch @moorscode. The file was moved. I will use the asset manager now for enqueueing the file.

**Comment by jcomack** [comment]
CR done 👍

**Comment by moorscode** [comment]
Acceptance done! 👍

**Pull request merged**
