### PR TITLE
Add SKU and URL to Individual Offers

### PR DESCRIPTION
**Pull request by jaredforth**
## Context

* We were having issues with Google differentiating the `offers` in our Schema on a Product page with multiple variants. Our SEO company told us to add the `sku` and `url` fields, which resolved the issues with Google. 

## Summary

This PR can be summarized in the following changelog entry:

* Add the `sku` and `url` to each `Offer` for product variants.  (320ab1c6b2b5a875a214bbc5957eddcf1293bf89)

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

* `classes/woocommerce-schema.php` - `add_individual_offers` function.

### CODE REVIEW

**Comment by jonoalderson** [comment]
Thanks for your contribution; this looks like a simple fix, and one I'd be happy for us to incorporate!

**Comment by jaredforth** [comment]
Great! Thank you! No rush on this at all, but do you have an ETA on when this would roll out?

**Comment by jonoalderson** [comment]
I'm afraid that we can't commit a timeline, but it's on our list to review. I'll keep you in the loop!

**Comment by IreneStr** [comment]
Hey @jaredforth,
I'm so sorry we lost track of your PR! We did however [implement the functionality that you proposed](https://github.com/Yoast/wpseo-woocommerce/commit/362097c7502deec1ecc653f8237334f23b32c961) in our 14.9 release. My apologies for losing your PR. I hope the fact that we did implement the functionality after all can be a bit of a consolation.

**Pull request closed without merging**
